[package]
name = "main"
version = "0.1.0"
authors = ["fdfd"]
[lib]
name="ConnectorVertical"
crate-type = ["cdylib"]
[dependencies]
lazy_static = "1.4.0"
libc = "*"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.96"
