
//------------------------------------------------------------------------------
// This code was generated by a tool.
//
//   Tool : Bond Compiler 0.12.1.0
//   Input filename:  D:\Rust\ConnectorVertical\RustCV\src\ConnectorVertical\Bond\Microsoft.SubstrateSearch.V2.Internal.SearchRequest.bond
//   Output filename: Microsoft.SubstrateSearch.V2.Internal.SearchRequest_types.cpp
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// <auto-generated />
//------------------------------------------------------------------------------

#include "Microsoft.SubstrateSearch.V2.Internal.SearchRequest_reflection.h"
#include <bond/core/exception.h>

namespace Microsoft
{
namespace SubstrateSearch
{
namespace V2
{
namespace Internal
{
    
    const ::bond::Metadata SearchRequest::Schema::metadata
        = SearchRequest::Schema::GetMetadata();
    
    const ::bond::Metadata SearchRequest::Schema::s_UserCacheKey_metadata
        = ::bond::reflection::MetadataInit(::bond::nothing, "UserCacheKey");

    
} // namespace Internal
} // namespace V2
} // namespace SubstrateSearch
} // namespace Microsoft
